#!/usr/bin/env bash
# start_chroot_script
# 
# Written by Todd E Johnson <todd@toddejohnson.net>
# GPL V3
########

# Source error handling, leave this in place
source /common.sh
install_cleanup_trap

#unpack /filesystem/home/pi /home/pi pi
#unpack /filesystem/home/root /root root
unpack /filesystem/boot /boot


apt-get update

# in case we are building from a regular raspbian image instead of the lite one...
remove_extra=$(remove_if_installed scratch squeak-plugins-scratch squeak-vm wolfram-engine python-minecraftpi minecraft-pi sonic-pi oracle-java8-jdk bluej libreoffice-common libreoffice-core freepats greenfoot nodered)
echo "removing:" $remove_extra
apt-get remove -y --purge  $remove_extra
apt-get autoremove -y
apt-get -y install git

#Config for TNCPi
sed -i 's/console=serial0,115200 //' /boot/cmdline.txt
echo 'enable_uart=1' >> /boot/config.txt


echo "--- Installing AX25"
apt-get -y install libax25 ax25-tools ax25-apps



if [ "$RMSPI_INCLUDE_RMSGW" == "yes" ]
then
  echo "--- Installing RMSGW"
  
  #  create the group for the gateway
  echo "Creating group rmsgw..."
	groupadd rmsgw

  #  create the gateway user
  echo "Creating user rmsgw..."
 	useradd -s /bin/false -g rmsgw rmsgw

  # lock the account to prevent a potential hole, unless the
  # owner is root
	echo "Locking user account rmsgw..."
	passwd -l rmsgw >/dev/null
	# while the account is locked, make the password to
	# never expire so that cron will be happy
	chage -E-1 rmsgw >/dev/null
  
  echo "Installing RMSGW Deps"
  apt-get -y install xutils-dev libxml2 libxml2-dev python-requests build-essential libax25-dev libx11-dev zlib1g-dev libncurses5-dev
  echo "Deps Installed"
  
  pushd  /home/pi/
    gitclone RMSPI_RMSGW_REPO rmsgw
    pushd rmsgw
      sudo -u pi make
      make install
    popd
  popd
  # Add RMS_ACI to Crontab
  echo "#6,36 *  * * *   rmsgw    /usr/local/bin/rmsgw_aci > /dev/null 2>&1" >> /etc/cron.d/rmspi
  # Install Logging
  cat << EOF > /etc/ax25/ax25d.conf
# RMS Gate
local0.info                     /var/log/rms
local0.debug                    /var/log/rms.debug
#local0.debug                   /dev/null
# (End)
EOF

fi

if [ "$RMSPI_INCLUDE_PAT" == "yes" ]
then
  wget -O pat_${RMSPI_PAT_VER}_linux_armhf.deb https://github.com/la5nta/pat/releases/download/v${RMSPI_PAT_VER}/pat_${RMSPI_PAT_VER}_linux_armhf.deb
  dpkg -i pat_${RMSPI_PAT_VER}_linux_armhf.deb
  systemctl_if_exists enable pat@pi.service

fi

# Unpack root at the end, so files are modified before
unpack /filesystem/root /

echo "---Enable AX.25"
systemctl_if_exists enable ax25.service

echo "---Enable WPA"
systemctl_if_exists enable check_wpa_link.service

### Fix SSH
echo "IPQoS 0x00" >> /etc/ssh/sshd_config

### Try and fix https://github.com/guysoft/OctoPi/issues/424
### Thanks guysoft/OctoPi!
sed -i "s@ExecStart=/usr/bin/ssh-keygen -A -v@ExecStart=/bin/bash -c ' /usr/bin/ssh-keygen -A -v >> /var/log/regenerate_ssh_host_keys.log 2>\&1'@g" /lib/systemd/system/regenerate_ssh_host_keys.service
sed -i "s@ExecStartPost=/bin/systemctl disable regenerate_ssh_host_keys@ExecStartPost=/bin/bash -c 'for i in /etc/ssh/ssh_host_*_key*; do actualsize=\$(wc -c <\"\$i\") ;if [ \$actualsize -eq 0 ]; then echo size is 0 bytes ; exit 1 ; fi ; done ; /bin/systemctl disable regenerate_ssh_host_keys'@g" /lib/systemd/system/regenerate_ssh_host_keys.service


