#!/bin/bash
# ax25-up.pi
# Ax25, rose, & mkiss - are pre-loaded via /etc/modules

# Set Sysctl values
sysctl -wq kernel.panic=30
sysctl -wq kernel.panic_on_oops=30

# Set defaults
BEACONINT=60

#Configure from /boot/rmspi.txt
if [ -e "/boot/rmspi.txt" ]; then
    echo "Using config from /boot/rmspi.txt"
    source "/boot/rmspi.txt"
fi

echo "Configured for ${CALL}${RMSSSID}"

cat << EOF > /etc/ax25/axports
#Port	 Call		Baud	PacLen	Window	Description
0	${CALL}		${AX25BAUD}	256	7	Radio - ${FREQ} MHz
EOF

cat << EOF > /etc/ax25/ax25d.conf
# /etc/ax25/ax25d.conf
[${CALL}${RMSSSID} via 0]
NOCALL  * * * * * * L
N0CALL  * * * * * * L
default * * * * * * -    rmsgw /usr/local/bin/rmsgw rmsgw -P 0 %U
# /etc/ax25/ax25d.conf (End)
EOF

cat << EOF > /etc/rmsgw/gateway.conf
GWCALL=${CALL}${RMSSSID}
GRIDSQUARE=${GRIDSQ}
CHANNELFILE=/etc/rmsgw/channels.xml
BANNERFILE=/etc/rmsgw/banner
LOGFACILITY=LOCAL0
LOGMASK=INFO
PYTHON=/usr/bin/python
EOF

echo "${RMSBANNER}" > /etc/rmsgw/banner

cat << EOF > /etc/rmsgw/channels.xml
<?xml version="1.0" encoding="UTF-8"?>
<rmschannels xmlns="http://www.namespace.org"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="file:///etc/rmsgw/channels.xsd">
  <channel name="0" type="ax25" active="yes">
    <basecall>${CALL}</basecall>
    <callsign>${CALL}${RMSSSID}</callsign>
    <password>${RMSPASSWORD}</password>
    <gridsquare>${GRIDSQ}</gridsquare>
    <frequency>${RMSFREQ}</frequency>
    <mode>0</mode>
    <autoonly>0</autoonly>
    <baud>1200</baud>
    <power>50</power>
    <height>10</height>
    <gain>0</gain>
    <direction>0</direction>
    <hours>24/7</hours>
    <groupreference>1</groupreference>
    <servicecode>PUBLIC</servicecode>
    <statuschecker>
      /usr/local/bin/rmschanstat \$type \$name \$callsign
    </statuschecker>
  </channel>
</rmschannels>
EOF

cat << EOF > /etc/rmsgw/sysop.xml
<sysops>
  <sysop>
    <Callsign>${CALL}</Callsign>
    <GridSquare>${GRIDSQ}</GridSquare>
    <SysopName>${RMSNAME}</SysopName>
    <StreetAddress1>${RMSADDR}</StreetAddress1>
    <StreetAddress2>${RMSADDR2}</StreetAddress2>
    <City>${RMSADDRCITY}</City>
    <State>${RMSADDRST}</State>
    <Country>${RMSCOUNTRY}</Country>
    <PostalCode>${RMSZIP}</PostalCode>
    <Email>${RMSEMAIL}</Email>
    <Phones>${RMSPHONE}</Phones>
    <Website>${RMSWEB}</Website>
    <Comments />
  </sysop>
</sysops>
EOF
cat << EOF > /etc/rmsgw/new-sysop.xml
<sysops>
  <sysop>
    <Callsign>${CALL}</Callsign>
    <GridSquare>${GRIDSQ}</GridSquare>
    <SysopName>${RMSNAME}</SysopName>
    <StreetAddress1>${RMSADDR}</StreetAddress1>
    <StreetAddress2>${RMSADDR2}</StreetAddress2>
    <City>${RMSADDRCITY}</City>
    <State>${RMSADDRST}</State>
    <Country>${RMSCOUNTRY}</Country>
    <PostalCode>${RMSZIP}</PostalCode>
    <Email>${RMSEMAIL}</Email>
    <Phones>${RMSPHONE}</Phones>
    <Website>${RMSWEB}</Website>
    <Comments />
  </sysop>
</sysops>
EOF

[ -d /home/pi/.wl2k ] || mkdir -p /home/pi/.wl2k
if [ -z ${PATSCHEDULE+x} ]
then
  SCHED="\"schedule\": {},"
else
  SCHED="\"schedule\": {\"${PATSCHEDULE}\": \"connect ${PATSCHEDULECONNECT}\"},"
fi

cat << EOF > /home/pi/.wl2k/config.json
{
  "mycall": "${CALL}",
  "secure_login_password": "${RMSPASSWORD}",
  "auxiliary_addresses": [],
  "locator": "${GRIDSQ}",
  "http_addr": "0.0.0.0:${PATPORT}",
  "motd": [
    "Open source Winlink client - getpat.io"
  ],
  "connect_aliases": {
    "telnet": "telnet://{mycall}:CMSTelnet@cms.winlink.org:8772/wl2k",
    "n9puz-10": "ax25://0/N9PUZ-10"
  },
  "listen": ["ax25"],
  "hamlib_rigs": {},
  "ax25": {
    "port": "0",
    "beacon": {
      "every": $(( BEACONINT * 60 )),
      "message": "Winlink P2P",
      "destination": "IDENT"
    },
    "rig": ""
  },
  "telnet": {
    "listen_addr": ":8774",
    "password": ""
  },
  ${SCHED}
  "version_reporting_disabled": false
}
EOF
chown -R pi:pi /home/pi/.wl2k/

# Port0 (Start)
echo "Start Port 0"

/usr/sbin/kissattach ${AX25DEV} 0 ${AX25IP} >/tmp/ax25-config.tmp
awk '/device/ { print $7 }' /tmp/ax25-config.tmp > /tmp/ax25-config-tmp
read Device < /tmp/ax25-config-tmp

# Install Parameter: P=128, W=10, TX-Delay=200
  /usr/sbin/kissparms -p 0 -r 128 -s 10 -l 20 -t 250

# Parms for a USER Port
cd /proc/sys/net/ax25/$Device/
echo 3000    > t1_timeout		# (Frack) /1000 = ? Sec
echo 1000    > t2_timeout 		# (RESPtime) /1000 = ? sec
echo 300000  > t3_timeout 		# (Check) /6000 = ? Min
echo 900000  > idle_timeout		# Idle Timer /6000 = ? min
echo 5       > standard_window_size	# Outstanding Frames
echo 8       > maximum_retry_count	# Max Retrys
echo 256     > maximum_packet_length	# Paclen
echo 0       > ax25_default_mode   
echo 0       > ip_default_mode
echo 0       > backoff_type
echo 2       > connect_mode
#echo 180000 > dama_slave_timeout
echo 32      > extended_window_size
echo 0       > protocol
# Port0 (End)

# Start "Other" Services

# Open Listen on Term 11
if [ "${AX25LISTEN}" == "yes" ]
then
  /usr/bin/axlisten -artc > /dev/tty11 &
fi

# Set Beacon for Port 0 
/usr/sbin/beacon \
	-d "BEACON" \
	-t ${BEACONINT} \
	0 \
	"RMS Gate ${CALL}${RMSSSID} ${RMSADDRCITY}, ${RMSADDRST}"

# Enable External Logons
  /usr/sbin/ax25d -l &
  echo "ax25d started"

# Start Mheard daemon
 /usr/sbin/mheardd -l -f -n 20
  echo "mheardd Started"

# AX25-up (End)
